### ISSUE TITLE
EXTERNAL_CMD implemented?

### ISSUE THREAD

**Issue by ag4ve** [mrash/fwknop#117]
According to the doc: 
http://www.cipherdyne.org/blog/2008/11/software-release-fwknop-1.9.9.html
EXTERNAL_CMD should be available, however there's still a note in the example fwknopd.conf that it's not implemented yet and the source seems to agree:
server/fwknopd_common.h:    //CONF_ENABLE_EXTERNAL_CMDS,
server/fwknopd_common.h:    //CONF_EXTERNAL_CMD_OPEN,
server/fwknopd_common.h:    //CONF_EXTERNAL_CMD_CLOSE,
server/fwknopd_common.h:    //CONF_EXTERNAL_CMD_ALARM,
server/cmd_opts.h:    //"ENABLE_EXTERNAL_CMDS",
server/cmd_opts.h:    //"EXTERNAL_CMD_OPEN",
server/cmd_opts.h:    //"EXTERNAL_CMD_CLOSE",
server/cmd_opts.h:    //"EXTERNAL_CMD_ALARM",

**Comment by mrash** [comment]
Current source in git master have completed this feature. A few loose ends (including adding material to the fwknop tutorial) will be fixed before the 2.6.8 release.

**Comment by mrash** [comment]
This has been completed with the 2.6.8 release. A blog post on ciperdyne.org along with the fwknopd man page has the details.
