### ISSUE TITLE
Allow base64-encoded keys in Android client

### ISSUE THREAD

**Issue by mrash** [mrash/fwknop#119]
Add support for base64-encoded keys in the Android client.

**Comment by oneru** [comment]
Would add that if we're supporting the big long ugly(AKA cryptographically secure) base64 keys, there needs to be an option to save the keys, or perhaps even load them from a config file. With some work, the android client could be a huge boost to usability.

**Comment by mrash** [comment]
Yes, completely agree.

**Comment by mrash** [comment]
Fwknop2 fixes this.
