### ISSUE TITLE
Add JuiceSSH plugin support for SPA/fwknop

### ISSUE THREAD

**Issue by mrash** [mrash/fwknop#120]
Rabin Yasharzadehe suggested to the fwknop mailing list that fwknop support be added to JuiceSSH via their new plugins capability:

http://www.androidpolice.com/2014/06/18/popular-android-ssh-client-juicessh-adds-support-for-community-plugins-and-you-can-get-three-of-them-right-now/

**Comment by solhuebner** [comment]
:+1: to add it to JuiceSSH

**Comment by oneru** [comment]
@PaulMaddox Is that offer of help still valid? I have a new version of fwknop on android in development over at https://github.com/oneru/Fwknop2

in SendSPA.java, I launch a connection using Juicessh, and it comes up, asks for the password, etc, and then goes to the background. I haven't seen a way to tell Juicessh not to background that new connection.  I want to use client.attach to bring that connection back to the foreground so the end user can work with it. My thought is to call client.connect in onSessionStarted, but it seems that onSessionStarted never gets called.

It's not the end of the world for the connection to be backgrounded, but it would be more intuitive for it to stay in the foreground.

Thanks,
Jonathan Bennett

**Comment by mrash** [comment]
Closing this issue since Jonathan's Fwknop2 Android client includes support for JuiceSSH.
