### ISSUE TITLE
SHA3-## (Keccak) support

### ISSUE THREAD

**Issue by steakknife** [mrash/fwknop#123]
Would be nice, because using even SHA-2 for long-lived (10 yr+), green-field projects wouldn't leave much of a security margin.

**Comment by oneru** [comment]
Is there an open source C implementation of keccak that we should use, or will we be rolling our own?  Ideal would be an official c keccak routine that we could use.  I'm just not sure if that exists with a license we can use.

**Comment by oneru** [comment]
https://github.com/gvanas/KeccakCodePackage/blob/master/Standalone/CompactFIPS202/Keccak-readable-and-compact.c looks like a potential candidate, and cc0 is GPL compatible.

**Comment by mrash** [comment]
@oneru has completed this for the upcoming 2.6.9 release.
