### ISSUE TITLE
fwknop using GPG_SIGNER -> Error 59 - Args contain invalid data

### ISSUE THREAD

**Issue by steakknife** [mrash/fwknop#136]
I might be doing something wrong . . . removing `GPG_SIGNER` generates a packet, while adding it does not.  

The only code path that generates this error is [fko_encryption.c#L400][fko_encryption.c#L400]

---- 
### Client side

`fwknop` built on OS X 10.9.5 with `brew install fwknop --HEAD` (@ 50434c5c4c9fe274430c560f83200061e545add2)

#### Terminal
```
0 ~ ❯❯❯ fwknop --verbose -n box0000

[+] Resolved external IP (via '/usr/local/bin/wget --secure-protocol=auto --quiet -U 'curl/7.30.0' -O - https://ifconfig.us') as: [redacted]
Enter passphrase for signing: [correct passphrase]
fwknop: fko_spa_data_final: Error 59 - Args contain invalid data: FKO_ERROR_INVALID_DATA_ENCRYPT_GPG_RESULT_MSGLEN_VALIDFAIL
1 ~ ❯❯❯
```

#### ~/.fwknoprc
```
[default]
GPG_SIGNER           <user's GPG key id> # commenting this out sends a packet
RESOLVE_URL          https://ifconfig.us/
HTTP_USER_AGENT      curl/7.30.0
WGET_CMD             /usr/local/bin/wget

[box0000]
SPOOF_USER           <someuser>
SPA_SERVER           <some.remote.box>
ACCESS               tcp/<port>
USE_GPG              Y
GPG_RECIPIENT        <box'es GPG key id>
RAND_PORT            Y
```

----
Irrelevant to the error / pedantic completeness:
#### /usr/local/etc/fwknop/access.conf

```
SOURCE                             ANY

GPG_REQUIRE_SIG                    Y
GPG_IGNORE_SIG_VERIFY_ERROR        N
GPG_HOME_DIR                       /usr/local/etc/fwknop/gnupg-home
GPG_DECRYPT_ID                     <box'es GPG key id>
GPG_DECRYPT_PW                     <box'es GPG passphrase>
GPG_REMOTE_ID                      <user's GPG key id> 
```

#### /usr/local/etc/fwknop/fwknopd.conf

```
PF_ANCHOR_NAME             fwknop;
PF_EXPIRE_INTERVAL         30;

PCAP_INTF                  xn0;
PCAP_FILTER                udp dst portrange 10000-65535;
```

----

### Notes 
1. HMAC disabled to simplify the example.

[fko_encryption.c#L400]: https://github.com/mrash/fwknop/blob/aae72a947026d96a43fe854079e92b9a31ad8b36/lib/fko_encryption.c#L400

**Comment by mrash** [comment]
Closing this bug. If this continues to be an issue, please provide details on the GPG key sizes per my previous note. Thanks.

**Comment by csirac2** [comment]
Steps to reproduce:

`gpg2 --gen-key`

- (1) RSA and RSA (default): 1
- What keysize do you want? (4096)
- Key is valid for? 1y
- Is this correct? y
- Real name: foobar
- Email address: foobar@foobar
- Comment:
