### ISSUE TITLE
System attempts to start `fwknopd` before network interfaces online

### ISSUE THREAD

**Issue by jmpolom** [mrash/fwknop#144]
On Fedora Server 1.0 using the fwknop-2.6.3-1.fc21 package, systemd attempts to start the fwknopd service before the network interfaces have come up. This results in fwknopd failing to start and potentially losing access to a system upon reboot/power cycle. This can be fixed by adding `network-online.target` to the `After=` line of the systemd service configuration file (`/lib/systemd/system/fwknopd.service`) for fwknop. This should be added to the installed systemd service file to prevent potential loss of system access.

**Comment by mrash** [comment]
Thanks for the bug report - I've emailed the fwknop RPM package maintainer about this.

**Comment by jmpolom** [comment]
Thanks for redirecting this to the proper location. I will follow-up with a
bug report against the package on the fedora bugzilla.

**Comment by jmpolom** [comment]
Cross-posted to Fedora bugzilla at #1195303 (
https://bugzilla.redhat.com/show_bug.cgi?id=1195303).

On Mon, Feb 23, 2015 at 9:30 AM, Jonathan M. Polom <s0nic0nslaught@gmail.com
> wrote:

> Thanks for redirecting this to the proper location. I will follow-up with
> a bug report against the package on the fedora bugzilla.
> On Feb 21, 2015 3:18 PM, "Michael Rash" <notifications@github.com> wrote:
>
>> Thanks for the bug report - I've emailed the fwknop RPM package
>> maintainer about this.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mrash/fwknop/issues/144#issuecomment-75390661>.
>>
>


-- 
Jon Polom

**Comment by mrash** [comment]
Great, thanks.

**Comment by mrash** [comment]
An engineer has been assigned to fix this bug by Red Hat. I have heard that ETA is 1-2 weeks. While fixing this in the Red Hat RPM, hopefully they will update to fwknop-2.6.5.

**Comment by mrash** [comment]
Looks like the bug was fixed in a new release of the fwknop-2.6.3 RPM:

http://koji.fedoraproject.org/koji/buildinfo?buildID=614828

**Comment by mrash** [comment]
Closing this issue per the previous comment.
