### ISSUE TITLE
Open multiple ports with one SPA packet

### ISSUE THREAD

**Issue by buruaga** [mrash/fwknop#146]
Hello, 
I recently updated fwknop  from 2.6.4 to 2.6.5 on a centOS 6.6 (iptables 1.4.7-14), and now (with 2.6.4 yes but i had another issues) I am not able to open multiple ports with a single operation, it opens just the first port listed.I attach obtained log.  If i send a similar SPA packet twice, first time opens one port and with the second one second port is opened( if rule for the first port is not expired, otherwise opens again the first port).It seems like only adds one rule per second?Any clue? 

Thank you!
Aitor A.

Log for one SPA packet in server:
Mar  5 08:12:47 localhost fwknopd[1880]: (stanza #1) SPA Packet from IP: 192.168.3.59 received with access source match
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd() (with execvpe()): running CMD: /sbin/iptables -t filter -L FWKNOP_INPUT -n
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd(): returning 0, pid_status: 0
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd() (with execvpe()): running CMD: /sbin/iptables -t filter -N FWKNOP_INPUT
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd(): returning 0, pid_status: 0
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd() (with execvpe()): running CMD: /sbin/iptables -t filter -L INPUT --line-numbers -n
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd(): returning 3, pid_status: 0
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd() (with execvpe()): running CMD: /sbin/iptables -t filter -L FWKNOP_INPUT --line-numbers -n
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd(): returning 0, pid_status: 0
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd() (with execvpe()): running CMD: /sbin/iptables -t filter -L FWKNOP_INPUT --line-numbers -n
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd(): returning 1, pid_status: 0
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd() (with execvpe()): running CMD: /sbin/iptables -t filter -L FWKNOP_INPUT --line-numbers -n
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd(): returning 3, pid_status: 0
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd() (with execvpe()): running CMD: /sbin/iptables -t filter -L FWKNOP_INPUT --line-numbers -n
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd(): returning 3, pid_status: 0
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd() (with execvpe()): running CMD: /sbin/iptables -t filter -L FWKNOP_INPUT --line-numbers -n
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd(): returning 0, pid_status: 0
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd() (with execvpe()): running CMD: /sbin/iptables -t filter -L FWKNOP_INPUT --line-numbers -n
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd(): returning 1, pid_status: 0
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd() (with execvpe()): running CMD: /sbin/iptables -t filter -L FWKNOP_INPUT --line-numbers -n
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd(): returning 3, pid_status: 0
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd() (with execvpe()): running CMD: /sbin/iptables -t filter -L FWKNOP_INPUT --line-numbers -n
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd(): returning 0, pid_status: 0
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd() (with execvpe()): running CMD: /sbin/iptables -A FWKNOP_INPUT -t filter -p 6 -s 192.168.3.59 -d 0.0.0.0/0 --dport 23 -m comment --comment _exp_1425539577 -j ACCEPT
Mar  5 08:12:47 localhost fwknopd[1880]: run_extcmd(): returning 0, pid_status: 0
Mar  5 08:12:47 localhost fwknopd[1880]: Added Rule to FWKNOP_INPUT for 192.168.3.59, tcp/22,tcp/23 expires at 1425539577
Mar  5 08:12:57 localhost fwknopd[1880]: run_extcmd() (with execvpe()): running CMD: /sbin/iptables -t filter -L FWKNOP_INPUT --line-numbers -n
Mar  5 08:12:57 localhost fwknopd[1880]: run_extcmd(): returning 0, pid_status: 0
Mar  5 08:12:57 localhost fwknopd[1880]: run_extcmd() (with execvpe()): running CMD: /sbin/iptables -t filter -D FWKNOP_INPUT 1
Mar  5 08:12:57 localhost fwknopd[1880]: run_extcmd(): returning 0, pid_status: 0
Mar  5 08:12:57 localhost fwknopd[1880]: Removed rule 1 from FWKNOP_INPUT with expire time of 1425539560

**Comment by mrash** [comment]
Thanks for reporting this, I will take a look over the next day or so.

**Comment by mrash** [comment]
What I would recommend on this is to see if there are any unexpired rules in the FWKNOP_INPUT chain by running "fwknopd --fw-list". If there are any such rules there, then they can be deleted either by restarting fwknopd, or by running "fwknopd --fw-flush". I will likely change how fwknopd processes old rules because this issue hints at the need for more rigorous processing here, but in the meantime I did add some additional test suite support for multi-port tests. I would be curious if these tests pass on your system, and you can run them as follows:

$ git clone https://github.com/mrash/fwknop.git fwknop.git
$ cd fwknop.git
$ ./extras/apparmor/configure_args.sh
$ make
$ su
# cd test
# ./test-fwknop.pl --include "multi port"

**Comment by buruaga** [comment]
Ok, i will do tests this week and report. What i found is that if i send a SPA packet with 2 ports to be opened , in function "rule_exists_no_chk_support"  it does check two times with the first port to be opened, so first rule with port 1 is added but when processes the second proto/port combo, rule exists because mentioned function checks again with the first port and finds just added rule.

What I did last week  is to create an IPT_RULE_ARG_MULTI:
#define IPT_RULE_ARGS_MULTI          "-t %s -p %i -s %s -d %s -m multiport --dports %i,%i -m comment --comment " EXPIRE_COMMENT_PREFIX "%u -j %s" SH_REDIR
and  process 2 prot/port cases in one time in "process_spa_request" function. Also edited "rule_exists_no_chk_support" .This is enough for my needs, but  i think that working with iptables multiport command is very interesting in enviroments with a lots of rules .

Thank you.

**Comment by mrash** [comment]
I know it has been a while, but fwknop-2.6.7 will likely fix this problem. Here is a -pre release of 2.6.7 that I think should have made progress towards a fix:

https://www.cipherdyne.org/fwknop/download/fwknop-2.6.7-pre1.tar.gz

GPG signature:

https://www.cipherdyne.org/fwknop/download/fwknop-2.6.7-pre1.tar.gz.asc

**Comment by mrash** [comment]
Closing this issue as it has been fixed for the upcoming 2.6.7 release.
