### ISSUE TITLE
Hostnames added to iptables rules?!?

### ISSUE THREAD

**Issue by mlawren** [mrash/fwknop#147]
Version is 2.6.0-2.1+b1 from current Debian 8.0/jessie/testing.

I have an issue that iptables rules are created by fwknopd using hostnames:

    Chain FWKNOP_INPUT (1 references)
    target     prot opt source               destination         
    ACCEPT     tcp  --  ulmg-5d846eba.pool.mediaWays.net  anywhere             tcp dpt:ssh /*_exp_1425645159 */

I would consider it bad practice to have filter rules relying on DNS. More importantly, when DNS is slow (or fails) it causes large delays for the output of `iptables -L`, or when the rules are triggered (when logging in via ssh for example).

**Comment by akerl** [comment]
Did you try running `iptables -L -n -v`?

Last I looked, adding a rule with a hostname causes a lookup *then* and iptables writes down the actual IP. It just does the reverse when you do `iptables -L` to show you the "prettier" name, the same way it converts "tcp dpt:22" to "tcp dpt:ssh"

**Comment by akerl** [comment]
Generally, SSH logins are delayed when DNS is down not because of iptables lookups but because the SSH daemon does reverse resolution on the connecting IP if UseDNS is enabled in your sshd_config

**Comment by mlawren** [comment]
ok, this might be a false alarm. I just discovered the `-n` option to iptables, which indicates that the lookups were being done locally, and so fwknopd is probably not at fault.

I still have a slow ssh login issue, which I guess is still due to slow DNS by my provider... But sorry for the noise.

**Comment by mlawren** [comment]
Wow - fast response - thanks! So my reply above reads funny because it is out of order...
