### ISSUE TITLE
fwknop client not working on osx mavericks

### ISSUE THREAD

**Issue by chuzzant** [mrash/fwknop#150]
I am running OSX Mavericks (10.9) .. and installed fwknop 2.6.5 via homebrew ..  I am trying to establish a session to a debian server accessible on the net, via a name that resolves .. 

Connectivity is not an issue, as I had a port enabled and was able to scp/ssh from the client before closing the port .. DNS resolution is not an issue either

Whether I run fwknop with or without '--use-wget-user-agent', the sequence below is unchanged 

`fwknop --use-wget-user-agent -A tcp/<ssh-port> --gpg-recip <fwknop-svr-keys> \ `
` --gpg-sign <fwknop-client-keys> -R -D host.example.com`

Fails, complaining: 
`[*] Use --wget-cmd <path> to specify path to the wget command`

So, I add the extra param .. 
`fwknop --use-wget-user-agent --wget-cmd=/usr/local/bin/wget -A tcp/<ssh-port> --gpg-recip \`
`<fwknop-svr-keyid> --gpg-sign <fwknop-client-keyid> -R -D host.example.com`

Then I get:
`fwknop: fko_set_gpg_recipient: Error 130 - The key for the given recipient was not found`
`GPG ERR: End of file`

Any suggestions on how I might debug this further ?  Thanks in advance

**Comment by akerl** [comment]
What's your gpg keyring look like? The first error is likely because your wget command isn't in the places that fwknop looks for it, and appears unrelated to the next error

**Comment by mrash** [comment]
Agreed. I think it would be good to ensure that both the recipient key (server) and the signing key (client) are included on the gpg keyring that the fwknop client is referencing. Note that you can set the path to the keyring if necessary with the --gpg-home-dir command line argument. Running gpg --list-keys would help make this clear I think.

**Comment by mrash** [comment]
Also, how are you specifying the key ID's? With strings like "8DC71BC6"?

**Comment by chuzzant** [comment]
Thanks akeri and mrash ..

Indeed you guys are right .. the keyring was missing the right keys .. and that was the main issue
(yes, I used strings like that for specifying key IDs) 

Thanks again .. 

fwknop is awesome .. I am mighty impressed that, with '-R' my NATed, DHCP obtained IP address was allowed ..

**Comment by mrash** [comment]
Excellent, thanks for following up on this. Let me know if you see any other issues.

**Comment by chuzzant** [comment]
No worries .. thanks for the prompt responses ..

**Comment by SkyWriter** [comment]
Just in case someone (like me) stumbles upon this again. I had fwknop stop working on Mac for me one day, just out of the blue. I figure it has to do with gpg (and/or its satellite libraries') updates, and what helped me out was:

    $ brew upgrade fwknop
