### ISSUE TITLE
Add --key-gen to fwknopd

### ISSUE THREAD

**Issue by mrash** [mrash/fwknop#154]
Jonathan Bennett suggested adding the --key-gen option to fwknopd to more easily support systems where the client is not installed. This makes sense, and will be added to the next release.

**Comment by oneru** [comment]
As soon as the patch for this is available, I'll backport it into fwknopd for openwrt, rather than waiting for the next release of fwknop.

**Comment by mrash** [comment]
Ok, sounds good. I have a good start on this already, and I'll push it to github tomorrow or so. Also, I'll plan to release 2.6.7 sooner than later to get this out into the hands of users.

**Comment by mrash** [comment]
This is nearly finished with commit ceb17139. I have a couple of additional minor tweaks to make though.

**Comment by oneru** [comment]
Testing it now. Ping me again when you're satisfied with it.

**Comment by mrash** [comment]
Made a change to handle --key-gen before config parsing, and also print keys to stdout instead of stderr. Test suite tests have been added and they are passing. Closing this issue, and thanks for the suggestion. Please let me know if you see any issues.
