### ISSUE TITLE
fwknopd on Fedora Server 21, Warning: could not use the 'comment' match

### ISSUE THREAD

**Issue by jmpolom** [mrash/fwknop#157]
Background: I previously reported a problem affecting the fwknop package in the Fedora repositories, where systemd would attempt to start the service before the network was online, causing it to fail. A fix was identified and submitted in the bug report against the package in the Red Hat bugzilla. They started shipping a modified unit file for fwknop a few weeks ago in an updated version of the package. I'm unsure if this issue is related, but the symptoms are similar.

fwknopd does not start after a reboot or from cold boot. The service fails and checking the service status with systemctl, it lists the status as failed and the only interesting bit of information reported is a line that says "Warning: could not use the 'comment' match".

I've tried adding some additional systemd service dependencies to the unit file, namely `NetworkManager.service` and `firewalld.service` (I ran `systemctl daemon-reload` after these changes obviously). However they did not resolve the issue of fwknopd not starting on boot.

If I run `systemctl start fwknopd` from the CLI after boot, the service starts fine, adds the appropriate iptables rules and I can successfully use SPA to expose ports remotely. It says that the 'comment' match is available.

I'm at a loss for what has changed or is causing fwknopd to not start on bootup. Any help troubleshooting this problem is appreciated as the work-around of starting fwknopd manually after boot is unacceptable.

**Comment by jmpolom** [comment]
Some additional information: this is package fwknop-2.6.5-2.fc21 on the Fedora Server flavor of F21. It appears that setting the config variable `ENABLE_IPT_COMMENT_CHECK` to a value of `N` in `fwknopd.conf` allows fwknopd to start successfully at boot time. I'm not sure why this is necessary now, as the config variable was present before but was left at the default setting.

If left at defaults, the fwknopd service WILL start after boot by manually running `systemctl start fwknopd` from the CLI.

I'll also add that I had to further change the `After=` line in the `fwknopd.service` file to mention `network.target` instead of `network-online.target` which was the fix roled out for the previously mentioned bug report. It appears the `network-online.target` is no longer being used on my system but `network.target` is.

**Comment by mrash** [comment]
Looks to me as though the fwknop package on Fedora still needs some work. Specifically, it is being built with '--with-firewalld' on the configure command line, and that option doesn't exist:

https://kojipkgs.fedoraproject.org//packages/fwknop/2.6.5/2.fc21/data/logs/x86_64/build.log

I suspect they meant to use the '--with-firewall-cmd' argument instead. The result of using this argument is that iptables is being found instead of firewalld as can be seen in that build log. fwknop has supported firewalld since 2.6.4, and they are building 2.6.5. Further, in the systemd config, I think the 'After=' should not reference ''iptables.service' or 'ip6tables.service'. Rather, I think it should look like this:

After=firewalld.service network-online.target

But, the above assumes that fwknop has been compiled with firewalld support instead of iptables support. If you have a Fedora21 system where you don't mind installation from sources just for testing, I think it would be interesting to clone the fwknop git repo, compile, and install. I'll email the Fedora package maintainer about the above as well.

**Comment by jmpolom** [comment]
Excellent summary of the situation. I will look into this and try building
a version of the package from the SRPM using the correct build options. I
will also open a bug on the Fedora bugzilla related to this issue.

I also agree with your comments regarding what should be in the systemd
unit file in the `After=` line. Neither `iptables.service` or
`ip6tables.service` should be referenced as typically these won't be
enabled on a F21 system since firewalld is default. However due to the way
that the `After=` directive works with systemd, there's little consequence
to leaving them there. If the services aren't enabled, systemd simply
ignores them. The `Requires=` directive on the other hand will require
those services be up and running.

If the package is changed to compile with support for firewalld, then the
unit file should include something more like `After=firewalld.service
network-online.target network.target` and `Requires=firewalld.service
network.target`.

I'm assuming you cannot build fwknop to support both iptables and
firewalld? The build options are mutually exclusive?

On Sat, Jun 13, 2015 at 10:33 PM, Michael Rash <notifications@github.com>
wrote:

> Looks to me as though the fwknop package on Fedora still needs some work.
> Specifically, it is being built with '--with-firewalld' on the configure
> command line, and that option doesn't exist:
>
>
> https://kojipkgs.fedoraproject.org//packages/fwknop/2.6.5/2.fc21/data/logs/x86_64/build.log
>
> I suspect they meant to use the '--with-firewall-cmd' argument instead.
> The result of using this argument is that iptables is being found instead
> of firewalld as can be seen in that build log. fwknop has supported
> firewalld since 2.6.4, and they are building 2.6.5. Further, in the systemd
> config, I think the 'After=' should not reference ''iptables.service' or
> 'ip6tables.service'. Rather, I think it should look like this:
>
> After=firewalld.service network-online.target
>
> But, the above assumes that fwknop has been compiled with firewalld
> support instead of iptables support. If you have a Fedora21 system where
> you don't mind installation from sources just for testing, I think it would
> be interesting to clone the fwknop git repo, compile, and install. I'll
> email the Fedora package maintainer about the above as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrash/fwknop/issues/157#issuecomment-111772862>.
>



-- 
Jon Polom

**Comment by mrash** [comment]
Regarding multiple firewall architectures, fwknopd only supports one at a time as defined at compile time. Typically this is a decent solution I think since the underlying firewall on a system doesn't change very often (although it does happen occasionally), and it also helps to maintain separation between the code that supports each firewall architecture.

**Comment by jmpolom** [comment]
I revised the RPM spec to use '--with-firewall-cmd' instead of incorrect option previously listed. Also changed systemd unit file so fwknopd starts after firewalld and network.target (previous iptables and ip6tables references were removed).

Installed rebuilt package from disk and left both `ENABLE_IPT_COMMENT_CHECK` and `ENABLE_FIREWD_COMMENT_CHECK` options as default in fwknopd.conf (default is Y). Service starts automatically upon reboot if enabled with systemd.

Since that fixes the problem, I'll file a bug report against the package on the Fedora bugzilla and provide them my updated spec and systemd unit file.

**Comment by mrash** [comment]
Sounds good, thanks.

On Sat, Jun 27, 2015 at 3:00 PM, Jon Polom <notifications@github.com> wrote:

> I revised the RPM spec to use '--with-firewall-cmd' instead of incorrect
> option previously listed. Also changed systemd unit file so fwknopd starts
> after firewalld and network.target (previous iptables and ip6tables
> references were removed).
>
> Installed rebuilt package from disk and left both ENABLE_IPT_COMMENT_CHECK
> and ENABLE_FIREWD_COMMENT_CHECK options as default in fwknopd.conf
> (default is Y). Service starts automatically upon reboot if enabled with
> systemd.
>
> Since that fixes the problem, I'll file a bug report against the package
> on the Fedora bugzilla and provide them my updated spec and systemd unit
> file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrash/fwknop/issues/157#issuecomment-116120635>.
>



-- 
Michael Rash | Founder
http://www.cipherdyne.org/
Key fingerprint = 53EA 13EA 472E 3771 894F  AC69 95D8 5D6B A742 839F

**Comment by Jakuje** [comment]
Hi,
thank you for investigation this issue. I got to this as late as now, since I watch now only our bugzilla.

I had to take that option from somewhere. And as I see in the readme [1], there is really --with-firewalld:
>   --with-firewalld=/path/to/firewalld
                          Specify path to the firewalld executable
                          [default=check path]
so probably documentation issue here upstream?

Also information, that the usage of firewalld x iptables is mutually exclusive is new for me. But as I think about it it makes sense. Firewalld is installed by default, so working with it is really nice. But there is no advantage for fwknop using firewalld except the cooperation with other tools that need to preserve iptables state. I think we can enforce using firewalld.

> Requires=firewalld.service network.target`.
I don't think that this is required. This should be covered by the After option

[1] https://github.com/mrash/fwknop/blob/master/README.md

**Comment by Jakuje** [comment]
To firewalld support, there were few concern about firewalld usage in firewalld-devel mailing list:
https://lists.fedorahosted.org/pipermail/firewalld-devel/2015-March/000172.html
I was thinking that I can make some patch proposal which would use native firewalld commands, but I didn't get to this yet (putting on my TODO list)

Now it looks quite awful when you see firewalld status and all that tests through firewall as failures:

>systemctl status firewalld.service  -l
[...]
Jun 29 10:31:58 localhost.localdomain systemd[1]: Started firewalld - dynamic firewall daemon.
Jun 29 10:31:59 localhost.localdomain firewalld[633]: 2015-06-29 10:31:59 ERROR: COMMAND_FAILED: '/sbin/iptables -w -C INPUT -t filter -j FWKNOP_INPUT' failed: iptables v1.4.21: Couldn't load target `FWKNOP_INPUT':No such file or directory
Jun 29 10:32:00 localhost.localdomain firewalld[633]: 2015-06-29 10:32:00 ERROR: COMMAND_FAILED: '/sbin/iptables -w -t filter -F FWKNOP_INPUT' failed: iptables: No chain/target/match by that name.
Jun 29 10:32:00 localhost.localdomain firewalld[633]: 2015-06-29 10:32:00 ERROR: COMMAND_FAILED: '/sbin/iptables -w -t filter -X FWKNOP_INPUT' failed: iptables: No chain/target/match by that name.
Jun 29 10:32:00 localhost.localdomain firewalld[633]: 2015-06-29 10:32:00 ERROR: COMMAND_FAILED: '/sbin/iptables -w -t filter -L FWKNOP_INPUT -n' failed: iptables: No chain/target/match by that name.
Jun 29 10:32:00 localhost.localdomain firewalld[633]: 2015-06-29 10:32:00 ERROR: COMMAND_FAILED: '/sbin/iptables -w -C INPUT -t filter -j FWKNOP_INPUT' failed: iptables: No chain/target/match by that name.
Jun 29 10:32:12 localhost.localdomain firewalld[633]: 2015-06-29 10:32:12 ERROR: COMMAND_FAILED: '/sbin/iptables -w -t filter -N FWKNOP_INPUT' failed: iptables: Chain already exists.
Jun 29 10:32:12 localhost.localdomain firewalld[633]: 2015-06-29 10:32:12 ERROR: COMMAND_FAILED: '/sbin/iptables -w -C FWKNOP_INPUT -t filter -p 6 -s 192.168.100.211 -d 0.0.0.0/0 --dport 22 -m comment --comment _exp_1435566761 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jun 29 10:34:12 localhost.localdomain firewalld[633]: 2015-06-29 10:34:12 ERROR: COMMAND_FAILED: '/sbin/iptables -w -t filter -N FWKNOP_INPUT' failed: iptables: Chain already exists.
Jun 29 10:34:12 localhost.localdomain firewalld[633]: 2015-06-29 10:34:12 ERROR: COMMAND_FAILED: '/sbin/iptables -w -C FWKNOP_INPUT -t filter -p 6 -s 192.168.100.211 -d 0.0.0.0/0 --dport 22 -m comment --comment _exp_1435566882 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).

**Comment by mrash** [comment]
Hi Jakuje,

Yes, that is a documentation issue in the README. The correct option to the
autoconf script is --with-firewall-cmd (since "firewall-cmd" is the command
line interface for firewalld), but I'll add a --with-firewalld synonym for
the next release to avoid confusion.

Sounds good about enforcing firewalld usage.

--Mike


On Mon, Jun 29, 2015 at 3:12 AM, Jakuje <notifications@github.com> wrote:

> Hi,
> thank you for investigation this issue. I got to this as late as now,
> since I watch now only our bugzilla.
>
> I had to take that option from somewhere. And as I see in the readme [1],
> there is really --with-firewalld:
>
> --with-firewalld=/path/to/firewalld
> Specify path to the firewalld executable
> [default=check path]
> so probably documentation issue here upstream?
>
> Also information, that the usage of firewalld x iptables is mutually
> exclusive is new for me. But as I think about it it makes sense. Firewalld
> is installed by default, so working with it is really nice. But there is no
> advantage for fwknop using firewalld except the cooperation with other
> tools that need to preserve iptables state. I think we can enforce using
> firewalld.
>
> Requires=firewalld.service network.target`.
> I don't think that this is required. This should be covered by the After
> option
>
> [1] https://github.com/mrash/fwknop/blob/master/README.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrash/fwknop/issues/157#issuecomment-116488992>.
>



-- 
Michael Rash | Founder
http://www.cipherdyne.org/
Key fingerprint = 53EA 13EA 472E 3771 894F  AC69 95D8 5D6B A742 839F

**Comment by mrash** [comment]
In response to that email thread, fwknopd does not rely on firewall rule
persistence across restarts of firewalld. Even if the firewalld service is
restarted, fwknopd will recover by recreating the appropriate chains and
jump rules. The only thing that would be missing is an ACCEPT rule that got
removed before a user had time to make a matching connection (to sshd or
whatever). This would be quite rare since it would require a firewalld
restart just after an SPA packet is received, but before the authenticated
connection is made.

The errors look like fwknopd is not compiled with firewalld support. The
--with-firewall-cmd autoconf option needs to be used per my previous
comment.

On Mon, Jun 29, 2015 at 4:52 AM, Jakuje <notifications@github.com> wrote:

> To firewalld support, there were few concern about firewalld usage in
> firewalld-devel mailing list:
>
> https://lists.fedorahosted.org/pipermail/firewalld-devel/2015-March/000172.html
> I was thinking that I can make some patch proposal which would use native
> firewalld commands, but I didn't get to this yet (putting on my TODO list)
>
> Now it looks quite awful when you see firewalld status and all that tests
> through firewall as failures:
>
> systemctl status firewalld.service -l
> [...]
> Jun 29 10:31:58 localhost.localdomain systemd[1]: Started firewalld -
> dynamic firewall daemon.
> Jun 29 10:31:59 localhost.localdomain firewalld[633]: 2015-06-29 10:31:59
> ERROR: COMMAND_FAILED: '/sbin/iptables -w -C INPUT -t filter -j
> FWKNOP_INPUT' failed: iptables v1.4.21: Couldn't load target
> `FWKNOP_INPUT':No such file or directory
> Jun 29 10:32:00 localhost.localdomain firewalld[633]: 2015-06-29 10:32:00
> ERROR: COMMAND_FAILED: '/sbin/iptables -w -t filter -F FWKNOP_INPUT'
> failed: iptables: No chain/target/match by that name.
> Jun 29 10:32:00 localhost.localdomain firewalld[633]: 2015-06-29 10:32:00
> ERROR: COMMAND_FAILED: '/sbin/iptables -w -t filter -X FWKNOP_INPUT'
> failed: iptables: No chain/target/match by that name.
> Jun 29 10:32:00 localhost.localdomain firewalld[633]: 2015-06-29 10:32:00
> ERROR: COMMAND_FAILED: '/sbin/iptables -w -t filter -L FWKNOP_INPUT -n'
> failed: iptables: No chain/target/match by that name.
> Jun 29 10:32:00 localhost.localdomain firewalld[633]: 2015-06-29 10:32:00
> ERROR: COMMAND_FAILED: '/sbin/iptables -w -C INPUT -t filter -j
> FWKNOP_INPUT' failed: iptables: No chain/target/match by that name.
> Jun 29 10:32:12 localhost.localdomain firewalld[633]: 2015-06-29 10:32:12
> ERROR: COMMAND_FAILED: '/sbin/iptables -w -t filter -N FWKNOP_INPUT'
> failed: iptables: Chain already exists.
> Jun 29 10:32:12 localhost.localdomain firewalld[633]: 2015-06-29 10:32:12
> ERROR: COMMAND_FAILED: '/sbin/iptables -w -C FWKNOP_INPUT -t filter -p 6 -s
> 192.168.100.211 -d 0.0.0.0/0 --dport 22 -m comment --comment
> _exp_1435566761 -j ACCEPT' failed: iptables: Bad rule (does a matching rule
> exist in that chain?).
> Jun 29 10:34:12 localhost.localdomain firewalld[633]: 2015-06-29 10:34:12
> ERROR: COMMAND_FAILED: '/sbin/iptables -w -t filter -N FWKNOP_INPUT'
> failed: iptables: Chain already exists.
> Jun 29 10:34:12 localhost.localdomain firewalld[633]: 2015-06-29 10:34:12
> ERROR: COMMAND_FAILED: '/sbin/iptables -w -C FWKNOP_INPUT -t filter -p 6 -s
> 192.168.100.211 -d 0.0.0.0/0 --dport 22 -m comment --comment
> _exp_1435566882 -j ACCEPT' failed: iptables: Bad rule (does a matching rule
> exist in that chain?).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrash/fwknop/issues/157#issuecomment-116532828>.
>



-- 
Michael Rash | Founder
http://www.cipherdyne.org/
Key fingerprint = 53EA 13EA 472E 3771 894F  AC69 95D8 5D6B A742 839F

**Comment by jmpolom** [comment]
Jakuje -- Having `Requires=firewalld.service` in the systemd unit file seems repetitive/unnecessary but it has a different meaning than the `After=` directive. In this case both firewalld and the network must be up for fwknopd to be of any use. I think we could only list firewalld as required since those need to be systemd services that can be activated, and targets can't be activated. By adding `Requires=firewalld.service` we can guarantee that firewalld will be started (even if it is stopped) when fwknop starts.

See the systemd unit file documentation here: http://www.freedesktop.org/software/systemd/man/systemd.unit.html

**Comment by Jakuje** [comment]
mrash: Thanks. It would be useful. I double checked how does it work on clean system, but still I see quite much red text in firewalld, but now also from fwknop service:
> Jun 30 09:14:49 localhost.localdomain fwknopd[598]: Error 0 from cmd:'/usr/bin/firewall-cmd --direct --passthrough ipv4  -t filter -L FWKNOP_INPUT -n': Error: COMMAND_FAILED: '/sbin/iptables -w -t filter -L FWKNOP_INPUT -n' failed: iptables: No chain/target/match by that name.
Is possible there is left some mess from non-firewalld installation of fwknop?
jmpolom: Thanks for clarification. It is not obvious from that bloat documentation on the first sight. I will push update today.

**Comment by mrash** [comment]
That error above looks ok actually. fwknopd tries to be careful to ensure that the chains it uses to add access rules exist, and I suspect you are seeing this at start-up when the FWKNOP_INPUT chain doesn't exist yet. The next command should be one to create the chain. If you are able to run the fwknop test suite, this would help give an indication of any problems. A single test that would be helpful to know whether it passes or not (it should) can be run like this:

cd test && ./test-fwknop.pl --include "Rijndael.*HMAC.*complete" --test-limit 1

**Comment by mrash** [comment]
One quick note - one of the errors mentioned above was being produced inappropriately because of a logging flag that should have been set to debug. This particular one has been fixed in 4169c6d4.

**Comment by mrash** [comment]
Any chance fwknop-2.6.7 could be packaged for Fedora? I suspect some of the things discussed in this issued have been fixed. Thanks.

**Comment by mrash** [comment]
fwknop-2.6.8 has been released. Perhaps the Fedora package can be updated? Closing this bug.

**Comment by zili55** [comment]
I'm still experiencing this bug on:
```
Ubuntu 20.04.2 LTS
fwknopd server 2.6.10, compiled for firewall bin: /usr/sbin/iptables
```
I fixed it via [comment](https://github.com/mrash/fwknop/issues/157#issuecomment-111748543).
