### ISSUE TITLE
Check server commands against whitelist

### ISSUE THREAD

**Issue by freegigi** [mrash/fwknop#159]
I have a suggestion: check server commands against a whitelist before execution, like a file containing the username and the allowed command.

Right now all command are allowed (by default as root). Let's say that I have the android client installed and I lose my device, everyone that has acces to it can run commands on my server. (ENABLE_CMD_EXEC is enabled because I use server commands).

Thank you.

**Comment by mrash** [comment]
Agreed, this would be a good feature to have. The old perl version of fwknop used to have the 'CMD_REGEX' feature that implemented this, and I'll add something similar. However, it will just be a substring match since I don't want to add more library dependencies.

**Comment by freegigi** [comment]
A simpler way to implement - use sudo. Let's say a config option CMD_EXEC_ALL_SUDO is defined, and if enabled, fwknop executes server commands prefixed with sudo (if they don't have sudo in the first place) as CMD_EXEC_USER, using the powerful sudoers syntax. It's the users job to restrict the commands in sudoers file.

This is probably easier to implement if you trust sudo's code to be secure.

**Comment by mrash** [comment]
Agreed, great idea. I'll put together a -pre release with this feature for testing before 2.6.7.

**Comment by freegigi** [comment]
Thank you!

**Comment by solhuebner** [comment]
:+1:

**Comment by mrash** [comment]
@solhuebner If I understand your question correctly, the arbitrary command feature is not enabled by default. Most SPA work flows are exactly what you describe where you want access to a service like SSH for a short period of time, and then access is removed. This is done by fwknopd via manipulation of firewall rules. This is a different capability than the command execution feature. To enable raw command execution, you have to set ENABLE_CMD_EXEC in the access.conf file in order for this to work.

**Comment by solhuebner** [comment]
Thank you for the clarification!
