### ISSUE TITLE
Execute command at successful SPA

### ISSUE THREAD

**Issue by kassius** [mrash/fwknop#172]
I would like to request for a a feature that executes a command on successful SPA. I heard of the EXTERNAL_CMD_OPEN which is about to be implemented, but I believe that it was planned having in mind a command for opening the firewall port?

What I really need is a command to warn the admin on open port (via email/ pushover etc) for security reasons. Maybe this could be a cool feature.

Thanks.

**Comment by mrash** [comment]
The CMD_CYCLE_OPEN functionality is complete, and will be released in the next version of fwknop (2.6.8). If you want to try this out, the code is available in git master.

In the use case you mention above, you can accomplish the goal in two ways:

1) fwknopd writes messages to syslog when a successful SPA packet causes a port to be opened. If you also want email alerts when this happens, you could use a log parser like 'swatch' or other similar pieces of software to send an email.
2) With the new CMD_CYCLE_OPEN functionality, you can have fwknopd execute a script that would open the port and also send an email alert.

**Comment by mrash** [comment]
fwknop-2.6.8 has been released, and the answers above should address the issue.
