### ISSUE TITLE
nat-local malfunctioning

### ISSUE THREAD

**Issue by kitrule** [mrash/fwknop#173]
While using fwknopd 2.6.7 with iptables I found nat-local SPA packets were producing rules in the incorrect iptables chain whenever a timeout was specified by the client.

Specifying a timeout of 0 produces message type 2 (NAT access msg), specifying other values produces message type 6 (Client timeout local NAT access msg), while not specifying a timeout at all produces message type 5 (Local NAT access msg).

Both message type 2 and 6 resulted in a rule being added to the forward chain instead of the input chain.

I originally described this behaviour against the new android client at oneru/Fwknop2#22

I can provide debug logs if it helps, I'm not sure if this has already been fixed in master but found no mention of it in existing/previous issues.

Somewhat separate, but related, I found nat-local was dependent on ENABLE_IPT_FORWARDING in fwknopd.conf despite the name/description suggesting that was limited to rules affecting the forward chain.

**Comment by mrash** [comment]
I will take a look.

**Comment by kitrule** [comment]
Thanks for fixing this, since upgrading to 2.6.8 I found a few related issues:

fwknopd.conf lists the default value for ENABLE_IPT_LOCAL_NAT as Y, however from testing it appears the default is N as fwknopd doesn't add the prerouting jump rule when started and refuses local nat SPA packets with "...requested NAT access, but is not enabled/supported".

Setting ENABLE_IPT_LOCAL_NAT to Y resolves these problems but also adds an unnecessary (only unnecessary when ENABLE_IPT_FORWARDING is left at its default of N) forward jump rule when started.
