### ISSUE TITLE
Generating HMAC Keys Without IP

### ISSUE THREAD

**Issue by primesoftware** [mrash/fwknop#174]
I have a question about generating HMAC keys. My plan is to use my laptop to connect to my home PC, but I do know the IP of the laptop ahead of time (i.e. if I am going to be at Starbucks its going to be a different IP than if I am at work) so I cannot issue the following command:

'''
fwknop -A tcp/22 -a 1.1.1.1 -D spaserver.domain.com --key-gen --use-hmac --save-rc-stanza
'''
unless I am able to transfer the key, which I won't be if I am away. What is the best and securest way to generate a key that would not be bound to an IP address as the IP is subject to change based on my location. I've read the docs, but I don't understand what's going on under the hood so much to say what's best.

**Comment by oneru** [comment]
Hello.  The HMAC key is a pre-shared key, intended to be generated ahead of time.  So on the machine that will be running fwknopd, you would run 
"
fwknop --key-gen
"
and it would generate a secure set of keys.  These keys would then go into the access.conf like:

"
SOURCE ANY
keytype Base 64 key
hkeytype Base 64 key
KEY_BASE64 <your_key>
HMAC_KEY_BASE64 <your_hmac>
"

Then you can run 
"
fwknop -A tcp/22 -R -D spaserver.domain.com --save-rc-stanza --key-base64-rijndael=<key> --key-base64-rijndael=<key>
"
on your laptop.  the "-R" flag tells fwknop to attempt to resolve your current public IP address, and send that within the SPA packet.

--Jonathan Bennett

**Comment by mrash** [comment]
Another thing to note is that you can always override the values in the ~/.fwknoprc file with command line arguments. So, you can initially create create the keys along with '-a 1.1.1.1' and then later on if you aren't actually coming from the 1.1.1.1 IP, you can just do 'fwknop -R -n spaserver.domain.com'. I'll keep this issue open for a few days just in case there are any other questions.

**Comment by primesoftware** [comment]
Thanks guys for the quick response and clarification! This is good software!

**Comment by primesoftware** [comment]
I'm running the following command on my client:

```
fwknop -A tcp/22 -a 192.168.1.3 -D 192.168.1.2 --key-base64-rijndael=::keyhere:: --key-base64-hmac=::hmackeyhere::
```
I'm testing locally just to see if the firewall rule gets added, but it doesn't. Fwknop-server is running, but I'm not seeing any syslog messages. Not sure what I am doing wrong here.

**Comment by primesoftware** [comment]
One last question....I noticed the following when typing fwknop --help

```
Specify the base64 encoded Rijndael key. Since
                             the password is visible to utilities (like 'ps'
                             under Unix) this form should only be used where
                             security is not important.
```
For both --key-base64-rijndael and --key-base64-hmac. Security is important to me so what is the right way to do this here? Should I load the keys from a file?

**Comment by oneru** [comment]
@primesoftware That warning refers primarily to a system with multiple users.  As an unprivileged process or user can execute the ps command, anyone logged into the same system as the fwknop client could see the keys that are used.  Saving the keys to your ~/.fwknoprc file would probably be slightly more secure.

**Comment by mrash** [comment]
Just to add to what @oneru said, once your keys are written to the ~/.fwknoprc file (which is more secure than specifying them on the command line), you can reference them via the name you gave for the SPA server. So, 1) create the keys and save them with --key-gen --save-rc-stanza, and 2) send SPA packets by referencing the stanza name with -n. This means you never have to use the --key-base64-rijndael or --key-base64-hmac args. Here is an example:

Create the keys and save them:

$ fwknop -A tcp/22 -R -D spaserver.domain.com --key-gen --save-rc-stanza

Now send an SPA packet like so:

$ fwknop -n spaserver.domain.com

(You'll need to transfer the generated keys to an access.conf stanza on the server side of things and restart fwknopd before sending the SPA packet.)

**Comment by primesoftware** [comment]
I'm going to close this thread down since I have everything working fairly well now. Thanks for the help!

**Comment by Murulidhar** [comment]
Hi,
May i know why server IP is must for generating the hmac key ? in the code also, there is no server ip arg sent for generating keys. But still it is restricted when no server ip is mentioned in the cmd line.

**Comment by mrash** [comment]
From the client, you can generate both encryption and HMAC keys with --key-gen at any time without specifying a server IP. However, to make these keys useful, you will need to transfer them to the SPA server. So, you will need to know a hostname or an IP for this server at some point. The examples in this issue illustrate how to generate the keys and save them to a stanza in the ~/.fwknoprc file so they can easily be used once they keys have been shared with the server. And, the client supports multiple stanzas so that multiple servers can be supported, and the server IP/hostname is used to label each stanza.

**Comment by Murulidhar** [comment]
i tried to generate the key without server ip but it is throwing error "Must use --destination unless --test mode is used". Please let me know what is the exact cmd line to generate the key without specifying the server ip.

**Comment by mrash** [comment]
You can just do:

$ fwknop --key-gen

This will print the keys on stdout. From there, you will need to associate them with a stanza in ~/.fwknoprc. You could just manually edit this file and add them I suppose.

Or, if you want to label a stanza as, say, 'somestring' and save the keys there, just do:

$ fwknop -n somestring --key-gen --save-rc-file

**Comment by Murulidhar** [comment]
ya got it, i just now experimented it after asking you. 
Thanks mrash.
