### ISSUE TITLE
allow hostname in nat-access message

### ISSUE THREAD

**Issue by oneru** [mrash/fwknop#176]
In a nat-access message, it would be useful to be able to specify the hostname of the internal host rather than the IP address.  It is quite possible that a desktop machine will change IP addresses on the local network.

**Comment by mrash** [comment]
Yes, this would be a good feature for sure.

**Comment by oneru** [comment]
@mrash I believe this feature is finished, Closing the bug.

**Comment by mrash** [comment]
@oneru There might be a slight issue with this patch, and the test suite I think may be able to help (some output removed below):

./test-fwknop.pl --include "basic.*\-nat"
[basic operations] [client save rc file] --nat-local................fail (1)
[basic operations] [client save rc file] --nat-local -f 1234........fail (2)
[basic operations] [client save rc file] --nat 192.168.10.1:12345...fail (3)
[basic operations] [client save rc file] --nat client timeout 1234s.fail (4)
[basic operations] [client save rc file] --nat client timeout 0s....fail (5)
[basic operations] [client save rc file] --nat-rand-port............fail (6)
[basic operations] [client save rc file] --nat-port 22211...........fail (7)
[Look for crashes] checking for segfault/core dump messages.........pass (8)


Looking at the output/1.test file shows the following in the SPA message string and nat access strings:

 Message String: 127.0.0.2,tcp/22
     Nat Access: ,22

The nat access string likely needs the IP as well. If you 'git checkout refs/tags/2.6.8' and recompile, the strings look like this:

 Message String: 127.0.0.2,tcp/22
     Nat Access: 127.0.0.1,22

**Comment by oneru** [comment]
@mrash Looking into this now.

**Comment by mrash** [comment]
Cool (no rush of course) - I'll offline for a bit this evening.
