### ISSUE TITLE
Ubuntu 15.10 issue

### ISSUE THREAD

**Issue by nikolay** [mrash/fwknop#177]
When I run `systemctl start fwknop-server`, I see in the logs:
```
Dec 03 01:47:14 ubuntu systemd[1]: Starting LSB: start and stop fwknopd...
Dec 03 01:47:14 ubuntu systemd[1]: Started LSB: start and stop fwknopd.
Dec 03 01:49:44 ubuntu systemd[1]: Started LSB: start and stop fwknopd.
```
Any idea how to fix this?

**Comment by mrash** [comment]
I need to get in touch with the fwknop package maintainer now that 2.6.8 is out. I'm hoping all distributions will upgrade, and include updated init scripts at the same time.

**Comment by mrash** [comment]
I've emailed the ubuntu-motu list about this.

**Comment by mrash** [comment]
Another solution is to use the systemd config file in extras/systemd/fwknopd.service. Just do:

# cp extras/systemd/fwknopd.service /lib/systemd/system/fwknopd.service
# ln -s /lib/systemd/system/fwknopd.service /etc/systemd/system/fwknopd.service

And then this should work:

# service fwknopd start

One thing to note is that this is for the fwknop-2.6.8 release from sources as opposed to the fwknop-server package. (Per the above I'm trying to get this updated.)

**Comment by mrash** [comment]
Closing this issue for now since the solution above should work (at least it worked for me on Ubuntu 15.10). Also, the upgrade to 2.6.8 will hopefully happen soon in the official Debian and Ubuntu repositories. If you test the solution above and run into any issues please let me know or reopen this bug.
