### ISSUE TITLE
Fwknop on Windows

### ISSUE THREAD

**Issue by primesoftware** [mrash/fwknop#182]
I have a couple questions about running fwknop on Windows as a client. 

1. I've read in the docs that Windows does not support PGP at the time, but the Morpheus UI allows for PGP Private / Public keys to be added. Are the docs out of date? (Admission: Haven't tried the Morpheus UI yet)

2. How do I generate an HMAC key on a Windows client to add to access.conf on Linux server? I've actually been using the server's HMAC in my SPA from the client, which I know is not technically correct. Or is it fine?

**Comment by mrash** [comment]
The Morpheus client is way old, and I don't think the PGP stuff ever actually worked in that UI, and it had other issues (like not supporting HMAC authenticated encryption). The current state of the art for fwknop client user interfaces is the UI from @oneru available here: https://incomsystems.biz/fwknop-gui/

It is cross-platform and supports pretty much all of the important client modes (HMAC's, IP resolution, NAT modes, stanza saving, base64-encoded keys, etc.). Although it doesn't yet support PGP / GPG, it has it where it counts in all other areas.

For generating an HMAC on the server and then using that in the client - that is completely fine.

**Comment by oneru** [comment]
@primesoftware @mrash Supporting GPG properly is in the roadmap for the new client.  I don't use fwknop in GPG mode, so it's been a low priority for me, but it'll happen.

**Comment by primesoftware** [comment]
@mrash @oneru Thanks guys! Big help! No hurry on GPG for me. HMAC works just fine.
