### ISSUE TITLE
Add fwknop option for no home folder

### ISSUE THREAD

**Issue by oneru** [mrash/fwknop#203]
Ran into an issue where running fwknop from a php script was failing because fwknop was trying to determine the home folder and failing.  Would be nice to have a mode where fwknop doesn't try to determine the home folder or do any of the associated actions.

**Comment by mrash** [comment]
Sounds like a good feature to have, will do.

**Comment by mrash** [comment]
I have a patch for this - will apply this evening.

**Comment by mrash** [comment]
Btw, let me know if there are any questions with this patch. Hopefully it captures the functionality you need.
