### ISSUE TITLE
Debian jessie package for fwknop-server pulls in lots of X11 dependencies

### ISSUE THREAD

**Issue by scotte** [mrash/fwknop#204]
I noticed while installing fwknopd on a Debian jessie headless server that the package pulls in a bunch of X11 dependencies which is unfortunate:

The following NEW packages will be installed:
  fwknop-server gnupg-agent gnupg2 hicolor-icon-theme libassuan0 libatk1.0-0 libatk1.0-data libcairo2 libdatrie1 libfko2
  libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgpgme11 libgraphite2-3 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libharfbuzz0b
  libjasper1 libksba8 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpixman-1-0 libpth20 libthai-data libthai0 libx11-6
  libx11-data libxau6 libxcb-render0 libxcb-shm0 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxdmcp6 libxext6 libxfixes3 libxi6
  libxinerama1 libxrandr2 libxrender1 pinentry-gtk2 shared-mime-info

It looks like the relevant dependency chain is:

fwknop-server
  Depends: libc6
  Depends: libfko2
  Depends: libpcap0.8
  Depends: iptables
  Depends: lsb-base
  Suggests: fwknop-apparmor-profile

libfko2
  Depends: libassuan0
  Depends: libc6
  Depends: libgpg-error0
  Depends: libgpgme11
  PreDepends: multiarch-support

libgpgme11
  Depends: gnupg2
  Depends: libassuan0
  Depends: libc6
  Depends: libgpg-error0
  PreDepends: multiarch-support
  Suggests: gpgsm

gnupg2
 |Depends: dpkg
  Depends: install-info
  Depends: gnupg-agent
  Depends: libassuan0
  Depends: libbz2-1.0
  Depends: libc6
  Depends: libcurl3-gnutls
  Depends: libgcrypt20
  Depends: libgpg-error0
  Depends: libksba8
  Depends: libreadline6
  Depends: zlib1g
  Suggests: <gnupg-doc>
  Suggests: parcimonie
  Suggests: xloadimage
  Recommends: libldap-2.4-2
  Conflicts: <gpg-idea>

gnupg-agent
 |Depends: pinentry-gtk2
 |Depends: pinentry-curses
  Depends: <pinentry>
    mew-beta-bin
    mew-bin
    pinentry-curses
    pinentry-gtk2
    pinentry-qt4
  Depends: libassuan0
  Depends: libc6
  Depends: libgcrypt20
  Depends: libgpg-error0
  Depends: libpth20
  Depends: libreadline6
 |Recommends: gnupg2
 |Recommends: gpgsm
  Recommends: gnupg
  Conflicts: <newpg>
  Breaks: gnupg2
  Breaks: gpgsm
  Replaces: gnupg2
  Replaces: gpgsm
  Replaces: <newpg>

Workaround is to install "pinentry-curses" to satisfy the pinentry dependency.

I'm not sure what can be done to improve this, but the workaround isn't obvious to someone not willing to chase the dependency chain. :-)

**Comment by mrash** [comment]
Thanks for submitting this issue. I think it would be if a Debian maintainer could take a look at this. I'm not sure if there is a current Debian maintainer for fwknop, but I'll check.

**Comment by scotte** [comment]
Thanks! I realized it's a bit vague of a bug for this source repo, since it's really around Debian packaging, but I thought it was worth reporting.

**Comment by jwilk** [comment]
This is a [known bug in gnupg-agent](https://bugs.debian.org/753163).

**Comment by scotte** [comment]
Thanks @jwilk - didn't see that one (and it's an old bug!). Since this will be fixed in the next Debian release via gnupg2 (clearly the root cause), I guess I"ll just close this - I never got around to submitting a bug for the debian package of fwknop-server (where adding an explicit dependency on pinentry-curses to satisfy the pinentry dependency would workaround it).... Since It's been 5 months, it's unlikely I'll ever get around to that, so I think appropriate and responsible action is to just close this bug. :-)
