### ISSUE TITLE
Please clarify license situation

### ISSUE THREAD

**Issue by Coacher** [mrash/fwknop#222]
Hello.

Almost every C file in lib/, client/, and server/ has the GPL-2+ header. README says that fwknop project as a whole is GPL-2. python/setup.py mentions GPL (no version == GPL1). Surprisingly lib/sha2.{h,c} files have the BSD header.

What is the real license(s)? If there are several licenses after all, then what license applies to each part of the project?

**Comment by oneru** [comment]
The project is gpl2+, as indicated in the headers.  Some files such as the sha2 and sha3 implementation are originally released under different licenses.  They contain those license texts as required by their original licenses.  The 3-clause BSD license is compatible with gpl2+, so no problem there.  Where it isn't explicit, we should make the license clearly gpl2+, such as the readme file.  Thanks for pointing out that discrepency

**Comment by Coacher** [comment]
Thank you for clarification. What about python module though? Is it GPL-2+ too? There is no license header in python files, but setup.py says GPL.

**Comment by oneru** [comment]
I believe they would be gpl2+ as well, but that is a question for @mrash to settle, as I believe he authored those files.

**Comment by mrash** [comment]
@damienstuart authored the python interface, and I believe he intended the license to be GPL2.

**Comment by damienstuart** [comment]
@mrash is correct.  My intention was the python code license would match that of the fwknop code (GPL2).  I have updated the python module code files accordingly.

**Comment by oneru** [comment]
Just a note to clarify, we're using GPL2+, not just the GPL2.

**Comment by mrash** [comment]
Oops, yes, GPL2+ because of the language allowing any later version at the user's discretion.

**Comment by damienstuart** [comment]
The language in the comments added at the top of the files was correct.  I just needed to change the GPL2 to GPL2+ in the "license =" line in the  setup.py code.  That should do it...

**Comment by oneru** [comment]
@mrash Would probably be good to tweak that in the README file as well.  I think that is the final change needed to close this issue.

**Comment by mrash** [comment]
Done.

**Comment by Coacher** [comment]
Thank you very much.
Could you also please update manpages:
https://github.com/mrash/fwknop/blob/master/doc/fwknop.man.asciidoc
https://github.com/mrash/fwknop/blob/master/doc/fwknopd.man.asciidoc

**Comment by Coacher** [comment]
More leftovers here:
https://github.com/mrash/fwknop/blob/master/client/fwknop.8.in
https://github.com/mrash/fwknop/blob/master/server/fwknopd.8.in
(just search for 'GPL')

**Comment by mrash** [comment]
I think this is fixed now in 5f15119190c230071cf8b8744936527dd25dd8b7

On Fri, Jun 3, 2016 at 10:43 AM, Coacher <notifications@github.com> wrote:

> More leftovers here:
> https://github.com/mrash/fwknop/blob/master/client/fwknop.8.in
> https://github.com/mrash/fwknop/blob/master/server/fwknopd.8.in
> (just search for 'GPL')
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/mrash/fwknop/issues/222#issuecomment-223598123>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAXNRAQYN-u4joJhy6s2_q1VjDIVaxgEks5qID1-gaJpZM4IrpKY>
> .
>



-- 
Michael Rash | Founder
http://www.cipherdyne.org/
Key fingerprint = 53EA 13EA 472E 3771 894F  AC69 95D8 5D6B A742 839F

**Comment by Coacher** [comment]
Almost. The last inconsistent piece seem to be this one: https://github.com/mrash/fwknop/blob/master/doc/libfko.texi#L188 (plus the corresponding TOC entry).

**Comment by mrash** [comment]
Fixed I think. Thanks.

On Sat, Jun 4, 2016 at 1:25 AM, Coacher <notifications@github.com> wrote:

> Almost. The last inconsistent piece seem to be this one:
> https://github.com/mrash/fwknop/blob/master/doc/libfko.texi#L188 (plus
> the corresponding TOC entry).
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/mrash/fwknop/issues/222#issuecomment-223737487>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAXNRPiCAeOTYx70M2j8XSWDRV9e5rvpks5qIQxBgaJpZM4IrpKY>
> .
>



-- 
Michael Rash | Founder
http://www.cipherdyne.org/
Key fingerprint = 53EA 13EA 472E 3771 894F  AC69 95D8 5D6B A742 839F

**Comment by Coacher** [comment]
It looks like license is updated everywhere now. Or at least in the most common places.
Thank you all very much.
