### ISSUE TITLE
FKO version 2.0.2 vs 3.0.0

### ISSUE THREAD

**Issue by fjoncourt** [mrash/fwknop#230]
Hello,

I was checking everything was working fine with the Debian package and I caught that both the Perl and Python bindings displayed a FKO version of (2.0.2). This value comes from lib/fko.h

#define FKO_PROTOCOL_VERSION "2.0.2"

However the FKO library is built as 3.0.0.
Is this normal? is there something I may have missed or misunderstood?

Regards,

**Comment by mrash** [comment]
Good catch, we'll get this fixed. The perl and Python modules needs to be updated. Thanks.

**Comment by fjoncourt** [comment]
Patched in the Debian package

**Comment by mrash** [comment]
Do you have a link handy for the Debian patch that fixed this? I'd like to apply it to master.

**Comment by fjoncourt** [comment]
Looks like it has been fixed by jonathan.

https://github.com/mrash/fwknop/commit/6d173f73e425cdfd452e7676e53a5091a44e859f#diff-0dc8ce697a0687426db8b1935311d3a1
