### ISSUE TITLE
Asymmetric key method issue

### ISSUE THREAD

**Issue by Murulidhar** [mrash/fwknop#236]
Hi,
In asymmetric key method of using fwknop, i am seeing error at server side.
"No stanza encryption mode match for encryption type : 2".
i followed the steps as mentioned in the below link
https://www.cipherdyne.org/fwknop/docs/fwknop-tutorial.html#fwknopd-start-stop
please let me know if i missed any steps.

**Comment by mrash** [comment]
Just checking if you have GPG keys set in a stanza within the /etc/fwknop/access.conf file on the server? Detailed instructions on GPG usage in fwknop are here: http://www.cipherdyne.org/fwknop/docs/fwknop-tutorial.html#fwknop-gpg

**Comment by Murulidhar** [comment]
you mean to say this line
#USE_GPG             N
It is set in /root/.fwknoprc and line not present in access.conf file.

**Comment by mrash** [comment]
If you want to use GPG for SPA, on the server side, your access.conf file needs to have a stanza like this:

SOURCE                     ANY
OPEN_PORTS                 tcp/22
REQUIRE_SOURCE_ADDRESS     Y
GPG_REMOTE_ID              1234ABCD;
GPG_DECRYPT_ID             ABCD1234;
GPG_DECRYPT_PW             <your decryption password> 
GPG_HOME_DIR               /root/.gnupg
FW_ACCESS_TIMEOUT          30


On the client, you need to execute fwknop like this (which will also add the appropriate config vars to your ~/.fwknoprc file):

$ fwknop -A tcp/22 --gpg-recip ABCD1234 --gpg-sign 1234ABCD -a 1.1.1.1 -D spaserver.domain.com --save-rc-stanza

**Comment by Murulidhar** [comment]
I have set everything except GPG_DECRYPT_PW, which password we have to give here ?

**Comment by mrash** [comment]
It's the password associated with the server's GPG key pair.

**Comment by Murulidhar** [comment]
but i dont rememeber whether i gave any password. is it passphrase ?
You mean to say If i dont give this password in the access.conf, it wont work at all ? 
and i am getting error because of this.

**Comment by mrash** [comment]
Yes, it is the passphrase for your server key pair. You can remove this passphrase and then set GPG_ALLOW_NO_PW, but this is not very common. Please review all of the steps listed here:

http://www.cipherdyne.org/fwknop/docs/fwknop-tutorial.html#fwknop-gpg

**Comment by mrash** [comment]
Closing this issue for now.
