### ISSUE TITLE
protecting docker containers

### ISSUE THREAD

**Issue by diseq** [mrash/fwknop#238]
i'm running fwknop on centos7. Although it works perfectly for host services (ssh) I have problems with the protection of docker exposed ports. (they are bypassing firewall-cmd)

i was trying to disable docker daemon mess up with iptables but by then i have to add all portforwarding rules manually

i'm not the expert, when it comes to firewalld.
What's your recommended way to achieve this?

**Comment by itoffshore** [comment]
this is how I [log into `lxc` containers behind `fwknop`](https://it-offshore.co.uk/security/53-stealth-your-ssh-port-ssh-into-lxc-containers)

**Comment by diseq** [comment]
Figured it out now: just for the interested
 - switched system (centos 7) to iptables
 - compiled fwknopd with iptables
 - start docker with '--iptables=false'

and have following rules added:

```
# nat rules
# allow docker outside access
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE

# different docker bridge networks
-A POSTROUTING -s 172.18.0.0/16 ! -o br-deadbeefdead-j MASQUERADE

# filter rules
# forward docker traffic
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT

# different docker bridge networks
-A FORWARD -o br-deadbeefdead-m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i br-deadbeefdead! -o br-deadbeefdead-j ACCEPT
-A FORWARD -i br-deadbeefdead-o br-deadbeefdead -j ACCEPT
```

then you control granular access to your containers with fwknopd and additional iptables rules

**Comment by mrash** [comment]
Interesting, thanks for posting this.
