### ISSUE TITLE
Does this work in Ubuntu 16.04

### ISSUE THREAD

**Issue by chepurko** [mrash/fwknop#240]
Hi, I've had great success running this on OpenWRT and CentOS 7 but I am seeing similar issues as [here](https://github.com/mrash/fwknop/issues/177).

```
$ sudo systemctl status fwknop-server.service 
● fwknop-server.service - LSB: start and stop fwknopd
   Loaded: loaded (/etc/init.d/fwknop-server; bad; vendor preset: enabled)
   Active: active (exited) since Mon 2016-11-07 23:46:56 UTC; 5min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1585 ExecStop=/etc/init.d/fwknop-server stop (code=exited, status=0/SUCCESS)
  Process: 1588 ExecStart=/etc/init.d/fwknop-server start (code=exited, status=0/SUCCESS)
    Tasks: 0
   Memory: 0B
      CPU: 0

Nov 07 23:46:56 ubuntu-1020-0138 systemd[1]: Starting LSB: start and stop fwknopd...
Nov 07 23:46:56 ubuntu-1020-0138 systemd[1]: Started LSB: start and stop fwknopd.
```

I've actually tried a) compiling from source (2.6.9) and ran into the problem that `libfko.so.3` isn't available, and b) downloading the latest 2.6.9 packages which are only available for 17.04 Zesty Zapus from Launchpad but I'm getting the same problem.

Nothing is coming into `/var/log/syslog` except for these "start/stop" messages and it's just not seeing any SPA packets received from remote clients so it doesn't seem to be starting up...

**Comment by fjoncourt** [comment]
Hi,

Could you check that **START_DAEMON** variable is set to **yes** in **/etc/default/fwknop-server**?

By default, it is set to no.

**Comment by chepurko** [comment]
Yep, that did it. Wish it was in some documentation though somewhere as this is special to Ubuntu. CentOS 7 doesn't have this file.

In addition to that, do you develop the `fwknop-apparmor-profile` package for Ubuntu? Because I also ran into this [bug](https://bugs.launchpad.net/ubuntu/+source/fwknop/+bug/1598506) and the error message was fixed by adding [these lines](https://bugs.launchpad.net/ubuntu/+source/fwknop/+bug/1598506/comments/2) to the apparmor profile.

**Comment by fjoncourt** [comment]
I will add a README file for Debian/Ubuntu to let people know about this file or maybe I will remove this feature in the next Debian release. I will see.

I have submitted this issue on the debian BTS
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844016

About the apparmor, I use the one provided by Michael that can be found here 
https://github.com/mrash/fwknop/blob/master/extras/apparmor/usr.sbin.fwknopd

I will provide a pull request against fwknop to add the mentionned lines

**Comment by chepurko** [comment]
Thanks a lot!
