### ISSUE TITLE
outdated url for GPG in automated environment

### ISSUE THREAD

**Issue by itoffshore** [mrash/fwknop#251]
Hi Michael - the [GPG in an automated environment link](http://www.gnupg.org/faq/GnuPG-FAQ.html#how-can-i-use-gnupg-in-an-automated-environment) on your [site docs](https://www.cipherdyne.org/fwknop/docs/fwknop-tutorial.html#verbose-example) should now be:

[https://www.gnupg.org/faq/gnupg-faq.html#automated_use](https://www.gnupg.org/faq/gnupg-faq.html#automated_use)

**Comment by mrash** [comment]
Fixed, thanks.
