### ISSUE TITLE
fwknopd not working with nftables

### ISSUE THREAD

**Issue by geo99918** [mrash/fwknop#352]
fwknopd is not working with newer kernels that use nftables.

see: https://forum.openwrt.org/t/fwknop-on-x86-64-22-03-2/143855

**Comment by bam80** [comment]
This probably is a duplicate of #107

**Comment by davidandreoletti** [comment]
@mrash This is definitely a duplicate of #107. Would you mind closing #352 ?

**Comment by mrash** [comment]
Yes, agreed, closing this one as a dupe of #107.
