### ISSUE TITLE
build from HEAD yields "fwknop: fko_set_spa_message: Error 100 - Invalid allow IP address in the SPA message data"

### ISSUE THREAD

**Issue by e40** [mrash/fwknop#363]
and the knocking does not happen.

I reset by to the HEAD before the activity today and `fwknop` works for me.  This is my config, in case it's now invalid:

```
[default]
ALLOW_IP            source

[gremlin]
SPA_SERVER          gremlinssh.foo.com
ACCESS              tcp/64208
NAT_ACCESS          XX.YY.ZZ.77,22
SPOOF_USER          foobar
```

**Comment by damienstuart** [comment]
Found the the commit that introduced the regression and reverted it.  What I thought was an innocuous change broke the decode/dcrypt processing of the SPA packet.

-Damien

**Comment by e40** [comment]
Sorry about that.  I guess I didn't test it full.  My bad.

It is curious how the seemingly dead code impacted things.
