### ISSUE TITLE
add knopwatchd to extras/ directory

### ISSUE THREAD

**Issue by mrash** [mrash/fwknop#6]
Kevin Hilton reported that knopwatchd is not included in the fwknop-2.0 sources distribution.  knopwatchd was part of the older perl fwknop distribution, and it wasn't promoted to the current fwknop C release.  The reasoning was that there are other programs that are designed for this (such as monit, etc.).  However, after thinking about it a bit, with fwknopd potentially deployed on small embedded systems where these other programs might not run, it seems like knopwatchd should be included in the extras/ directory at least. knopwatchd is extremely lightweight, and includes a feature set that is something controlled by the fwknop developers.

**Comment by oneru** [comment]
@mrash @damienstuart Almost all current distros now have an option to watchdog and restart a service.  Openwrt even has support for this in its init system.  

Suggest leaving knopwatchd as legacy code, not including in /extras, and closing this issue.

**Comment by mrash** [comment]
Agreed.
