### ISSUE TITLE
fwknop client: Support reading the passphrase from STDIN

### ISSUE THREAD

**Issue by hlein** [mrash/fwknop#74]
It would be helpful if the fwknop client could read the passphrase from STDIN.  Then one could do something like:

gpg -d passphrasefile.pgp | fwknop -R -n myserver

...And in the common case, gpg-agent would handle gpg's need for a passphrase.

Perhaps this could be implemented simply by making -G accept '-' to mean stdin.

Or perhaps a new --fd option or somesuch, so the usage in a simple pipeline would be --fd 0.

**Comment by VanagaS** [comment]
I use fwknop client 2.6.7, FKO protocol version 2.0.2 on CentOS 7.6 and the command I use to connect to server is:

fwknop A tcp/22 --gpg-recip XXXXX --gpg-sign YYYYY -a 10.10.10.10 -D 10.20.20.20 -p 36 -P udp

I get two password prompts, one right after the command and second a curses based GPG box.
Any text can be given at the first password prompt (even wrong password) as it only accepts the password given in the GPG box. 

Now, we wanted to automate it and when fwknop command above is supplied with --stdin or --fd 0, it skips the first password prompt but still brings up the GPG box. I'm not clear if I missed something but I'm unable to get rid of the GPG curses box to wrap it within a script.

Any suggestions will be of great help, thank you!
