### ISSUE TITLE
Feature Request: Ipsets

### ISSUE THREAD

**Issue by ReubenM** [mrash/fwknop#83]
First, a big thanks for all the work going into the 2.x codebase. This is great.

I wanted to request support for the option to utilize ipsets for managing access instead of adding rules to an iptables chain. This would allow much better integration with other firewall tools (in my case, shorewall) as well as keeping the iptables filters more manageable.

**Comment by mrash** [comment]
This is supported now as of 2.6.8, and a blog post on cipherdyne.org provides an example integration with ipset.
