### ISSUE TITLE
Android client limited IP selection

### ISSUE THREAD

**Issue by tsankuanglee** [mrash/fwknop#9]
First, excellent excellent work! My security maintenance cost dropped a lot because fwknopd. (I had to upgrade my storage just to prevent disk full from bad login log).

I have two feature requests on the Android client:

1. Can there be an option to manually input the source IP, in addition to auto-detect?  I use my phone to knock open the port but then use my laptop to actually do the ssh session. They have different IPs.

2. Can the server port be assigned? The code says "Until we make this settable." (android/project/jni/fwknop/fwknop_client.c line 105). Is it the current library limitation or just the client/wrapper implementation?

Thanks!

**Comment by mrash** [comment]
This has been fixed by Jonathan Bennett's new Fwknop2 Android app.
